name: MyPy

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: MyPy Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.930
        with:
          mypy_flags: '--config-file .mypy.ini'
