name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Cache installation
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      run: |
        pytest --disable-pytest-warnings --cov-report=term --cov=utils/ tests/ | tee .pytest.txt
    - name: Handle test results
      run: |
        score=$(cat .pytest.txt | grep TOTAL | tr -s ' ' | cut -d ' ' -f 4)
        n_failures=$(cat .pytest.txt | grep failed | cut -d ' ' -f 2)
        echo "Pytest finds $n_failures failure(s)"
        echo "Tests coverage is $score"
        color=$(python utils/github_actions/pytest_manager.py --score=$score --n_failures=$n_failures)
        echo "PYTEST_COLOR=$color"
        echo "PYTEST_COLOR=$color" >> $GITHUB_ENV
        echo "PYTEST_SCORE=$score"
        echo "PYTEST_SCORE=$score" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 106c646ac67294657bccf02bbe22208f
        filename: gan_facies_modeling_coverage.json
        label: Coverage
        message: ${{ env.PYTEST_SCORE }}
        color: ${{ env.PYTEST_COLOR }}
        style: flat
        namedLogo: github
        logoColor: '#959DA5'
        labelColor: '#343B42'
